version: '3.8'

services:
  oem-e2e-poc-public:
    image: oem-e2e-poc-public
    container_name: oem-e2e-poc-public
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html
    env_file:
      - .env.example
